apiVersion: apps/v1
kind: Deployment
metadata:  
  labels:
    run: poi
  namespace: api
  name: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      run: poi  
  template:
    metadata:      
      labels:
        run: poi
    spec:
      containers:
      - image: registryrxt3043.azurecr.io/team1/poi:1.0
        name: poi
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/secrets"
          readOnly: true
        env:
        - name: SQL_USER
          value: "sqladminrXt3043"
        - name: SQL_SERVER
          value: "sqlserverrxt3043.database.windows.net"
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-kvname"
