apiVersion: v1
kind: Service
metadata:
  labels:
    app: tripviewer
  name: tripviewer-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: tripviewer
  type: LoadBalancer