apiVersion: v1
kind: Service
metadata:
  labels:
    app: userprofile
  name: userprofile
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: userprofile
  type: ClusterIP
