kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-same-namespace
  namespace: api
spec:
  podSelector:
    matchLabels:
      app: tripviewer
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: team1-aks-ingress-nginx-ingress
      namespaceSelector:
        matchLabels:
          type: ingress
    ports:
      - port: 80
